SMS_18/SMS_18/urls.py
from django.conf.urls import url,include
from django.contrib import admin
#from sms_auth.views import home
from .views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^$', index, name='index'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^auth/', include('sms_auth.urls', namespace="auth")),
    ]

urlpatterns += [
    url(r'', include('main.urls', namespace="main")),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SMS_18/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test$', views.test, name='test'),
    url(r'^apiforefa$', views.apiforefa, name='apiforefa'),
    url(r'^getconversionrate$', views.getconversionrate, name='getconversionrate'),
    url(r'^gameswitchstatus$', views.gameswitchstatus, name='gameswitchstatus'),
    url(r'^game$', views.game , name='game'),
    url(r'^news$', views.news , name='news'),
    url(r'^buystocks/(?P<id>\d+)$', views.BuyStocks , name='BuyStocks'),
	url(r'^buy/(?P<id>\d+)$', views.buy, name='buy'),
    url(r'^sellstocks/(?P<id>\d+)$', views.SellStocks , name='SellStocks'),
	url(r'^sell/(?P<id>\d+)$', views.sell, name='sell'),
    url(r'^userprimarydetails$', views.UserPrimaryDetails , name='UserPrimaryDetails'),
    url(r'^userstockdetails$', views.UserStockDetails , name='UserStockDetails'),
    url(r'^stocksprimarydata$', views.StocksPrimaryData , name='StocksPrimaryData'),
    url(r'^stockdata/(?P<id>\d+)$', views.StockData , name='StockData'),
    url(r'^leaderboard$', views.leaderboard , name='leaderboard'),
    url(r'^lbdata$', views.LBdata , name='LBdata'),
    url(r'^createProfile$', views.createProfile , name='createProfile'),
    url(r'^profile$', views.profile , name='profile'),
    url(r'^international$', views.international , name='international'),
    url(r'^register$', views.register , name='register'),
    url(r'^login$', views.login , name='login'),
    url(r'^logout$', views.logout , name='logout'),
    url(r'^userlogin$', views.userLogin , name='userLogin'),
    url(r'^getnewspost$', views.getnewspost , name='getnewspost'),
]

SMS_18/main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime  

class UserProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE) #extending user model
	name = models.CharField(max_length=100)	#username as per the db
	mail_id=models.CharField(max_length=100) #will get from app so no checks are required
	balance=models.IntegerField(default=100) #this will contain the current balance throughout 
	net_worth=models.IntegerField(default=0)

	def __str__(self):
		return self.name

class Stock(models.Model):
	product_name = models.CharField(max_length=100) #from manforce to mrf, anything in between xD
	stock_price = models.IntegerField(default=0) #Stock price at any instant
	market_type = models.CharField(max_length=10, null=False, choices=(("BSE",'"BSE"'),("NYM",'"NYM"')),default="BSE")
	price_trend = models.IntegerField(default=0)
	initial_price = models.IntegerField(default = 0)
	#first two digits will be ones and tens representatives... others decimal

	def __str__(self):
		return self.product_name

class StockPurchased(models.Model):
	owner = models.ForeignKey('UserProfile' , on_delete=models.CASCADE) #stock purchased by which user
	stockid = models.ForeignKey('Stock' , on_delete=models.CASCADE) #which stock purchased by user
	number_of_stocks = models.IntegerField(default=0) #how many stocks were purchased
	# TODO: Average stock price: Call the Stock with stock_id, calculate the total and then avg. price.
	average_price = models.IntegerField(default=0)
	
	def __str__(self):
		return str(self.number_of_stocks)


class GameSwitch(models.Model):
	switch_name=models.CharField(null=False,max_length=10) #We will have only one switch called 'Main'
	game_status= models.CharField(null=False, choices=(("live",'"live"'),("closed",'"closed"')),max_length=100,default="closed") 

	def __str__(self):
		return self.switch_name

class NewsPost(models.Model):
	post_text=models.CharField(null=False,max_length=4000)
	time_of_post=models.DateTimeField(default=datetime.now, blank=True)


		
class ConversionRate(models.Model):
	var_name = models.CharField(null=False,max_length=100,default="main")
	conversion_rate = models.IntegerField(default=0)

	def __str__(self):
		return self.var_name

SMS_18/main/forms.py
from django import forms
import re
from django.core import validators

class TransactionForm(forms.Form):
	stockname = forms.CharField(required = True,max_length=50)
	units = forms.IntegerField(required = True)

SMS_18/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse, Http404 ,HttpResponseForbidden, HttpResponseRedirect
from .models import UserProfile, GameSwitch, Stock, StockPurchased, NewsPost, ConversionRate
from django.shortcuts import redirect, render_to_response
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.contrib import auth
from django.db import IntegrityError
from django.contrib.auth.models import User
import json
from .forms import TransactionForm
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from algoscript import algo

key = "9bBo3YmHufzvSYWjbtkURd" 

def index(request):#just a render view
    if request.user.is_authenticated():
        return redirect('main:game')
    else:
        return redirect('auth:form')
        # resp={
        #     'error':'The user is not registered yet.'
        # }
        # return HttpResponse(json.dumps(resp), content_type = "application/json")

def test(request):
	algo()
	return HttpResponse("Cool")

def game(request):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/gamepage.html')

def leaderboard(request):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/leaderboard.html')

def buy(request, id):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/buy.html', {'id':id})

def sell(request, id):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/sell.html', {'id':id})

def profile(request):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/profile.html')

def international(request):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/international.html')

def news(request):#just a render view
    if not request.user.is_authenticated():
        resp={
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    return render(request, 'main/news.html')    



# Register and login functions not working!

@csrf_exempt
def register(request):
    if request.method == 'POST':
        data = request.POST
        try:
            obj = User.objects.get(username=data.get('username'))
            return HttpResponse(json.dumps({"status":"fail", "url":reverse('main:index')}), content_type="application/json")
        except User.DoesNotExist:
            user = User.objects.create_user(data.get('username'), data.get('email'), data.get('password'))
            user.save()
            userProf = UserProfile.objects.create(user=user, name=data.get('username'), mail_id=data.get('email'))
            userProf.save()
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            django_login(request,user)
            return HttpResponse(json.dumps({"status":"success", "email":user.email, "url":reverse('main:game')}), content_type="application/json")
    return redirect('main:index')

@csrf_exempt
def login(request):
    if request.method == 'POST':
        data = request.POST
        print(data.get('username'))
        print(data.get('password'))
        print(data)
        user = authenticate(username=data.get('username'), password=data.get('password'))
        django_login(request, user)
        if user is None:
            return HttpResponse(json.dumps({"status":"fail", "url":reverse('main:index')}), content_type="application/json")
        else:
            return HttpResponse(json.dumps({"status":"success", "email":user.email, "url":reverse('main:game')}), content_type="application/json")
    return redirect('main:index')

def logout(request):
    django_logout(request)
    return redirect('main:index')
    del request.session['email']

# TODO: Usage??
def createProfile(request):
    try:
        userProf = UserProfile.objects.get(user=request.user)
    except:
        userProf = UserProfile.objects.create(user=request.user, name=request.user.get_full_name(), mail_id=request.user.email)
    return render(request, 'main/profileCreate.html', {'email': request.user.email, 'url':reverse('main:game')})


### (apb7, priyankjairaj100): Do not change these view functions.
# TODO: Setup a POST method with a key and email_id for user verification.

# TODO(priyankjairaj100): Implement a check on balance (>=0)
@csrf_exempt
def BuyStocks(request, id):
    global key
    user_key = request.POST.get('key')
    if user_key != key:
        resp = {
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type="application/json")
    email = request.POST.get('email')
    current_user = UserProfile.objects.get(mail_id=email)
    # TODO(apb7): Remove the POST check here and put it at the top.
    if request.method == 'POST':
        data = request.POST
        stock_info = Stock.objects.get(id=id)
        
        transaction_cost = int(data['units'])*stock_info.stock_price
        if( current_user.balance < transaction_cost ):
            resp={
                'error':'Not sufficient balance to proceed the transaction'
            }
            return HttpResponse(json.dumps(resp), content_type="application/json")
        current_user.balance -= transaction_cost

        current_user.save()

        try:
            current_stock = StockPurchased.objects.get(owner_id=current_user.id, stockid=stock_info)
        except:
            current_stock = StockPurchased.objects.create(owner_id=current_user.id, stockid=stock_info)

        new_number = current_stock.number_of_stocks+int(data['units'])
        current_stock.average_price = (current_stock.average_price*current_stock.number_of_stocks+ transaction_cost)/new_number 
        current_stock.number_of_stocks = new_number
        current_stock.save()
        print(current_stock)
        resp = {
            'message': 'SUCCESS: The user purchased the stock.'
        }
        return HttpResponse(json.dumps(resp), content_type="application/json")
        #return redirect('main:game')


@csrf_exempt
def SellStocks(request, id):
    global key
    user_key = request.POST.get('key')
    if user_key != key:
        resp = {
            'error':'The user is not registered yet.'
        }
        return HttpResponse(json.dumps(resp), content_type="application/json")
    email = request.POST.get('email')
    current_user = UserProfile.objects.get(mail_id=email)
    stock_info = Stock.objects.get(id=id)
    try:
        current_stock = StockPurchased.objects.get(owner=current_user.id, stockid=stock_info)
    except StockPurchased.DoesNotExist:
        current_stock = None

    if request.method == 'POST' and current_stock is not None:
        data = request.POST
        stock_info = Stock.objects.get(id=id)
        if current_stock.number_of_stocks >= int(data['units']):
            transaction_cost = int(data['units'])*stock_info.stock_price
            current_user.balance += transaction_cost
            current_user.save()
            #current_stock = StockPurchased.objects.get(owner=current_user.id, stockid=stock_info)
            new_number = current_stock.number_of_stocks - int(data['units'])
            if new_number is 0:
                current_stock.delete()
            else:
                #current_stock.save()
                # new_number = current_stock.number_of_stocks+int(data['units'])
                #current_stock.average_price = ((current_stock.average_price * current_stock.number_of_stocks) + transaction_cost)/new_number 
                current_stock.number_of_stocks = new_number
                current_stock.save()
            resp = {
                'message': 'SUCCESS: The user sold the stock.'
            }
            return HttpResponse(json.dumps(resp), content_type="application/json")
        else:
            resp = {
                'error': 'FAILURE: The user does not have enough stocks to sell.'
            }
            return HttpResponse(json.dumps(resp), content_type="application/json")
        
    elif request.method == 'POST' and current_stock is None:
        resp = {
            'error': 'The user does not have any stocks to sell'
        }
        return HttpResponse(json.dumps(resp), content_type="application/json")


# This view will provide details of the user. No template rendered.
@csrf_exempt
def UserPrimaryDetails(request):
    global key
    user_key = request.POST.get('key')
    if user_key != key:
        resp={
            'error':'The user is not registered yet.'
        }
        print("error")
        return HttpResponse(json.dumps(resp), content_type = "application/json")
    email = request.POST.get('email')
    current_user = UserProfile.objects.get(mail_id = email)
    resp={

SMS_18/main/templates/main/gamepage.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Stock Market Stimulation</title>
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
	<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/home.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/template.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
	<div class="container">
			<div class="header">
				<!-- <div class="title"> <span> STOCK MARKET SIMULATION </span> </div> -->
				<div class="profile">
					<div class="user user1" id="userName"></div>
					<div class="user user2">Balance: &#8377 
						<span  id="userBalance"></span>
						<span class="conversionRate"> (&#36 1 = &#8377 <span id="conversionRate"></span>)</span>
						<span class="hamburgerIcon"onclick="openNav()">&#9776;</span></div>
				</div>
				<div class="navbar">
					
					<a href="{% url 'main:game' %}"><div class="nav active"><span>Indian</span> </div> </a>
		  			<a href="{% url 'main:international' %}"> <div class="nav"><span>International</span> </div> </a>

				</div>
			</div>
		<div class="main">
			<div class="stock">
				<div class="shown">
					<div class="name"><b>Stock Name</b></div>
					<div class="price"> <span><b>Stock Price</b></span>
										<!-- <span id="increasePrice"> &#x25B2; </span>
										<span id="decreasePrice"> &#x25BC; </span> -->
					</div>
				</div>
				<!-- <div class="hidden">
					<div class="buy" id="myBtn"><button onclick="modalOpen()">BUY</button> </div>
					
					<div class="sell" id="myBtn"><button class="button" onclick="modalOpenS()">SELL</button></div>

					 <div class=""> <button id="myBtn" onclick="modalOpen()">Open Modal</button> </div>
				</div> -->
			</div>
		</div>

		
		<div class="sideBar">
			<div id="mySidenav" class="sidenav">
				<div class="closebtndiv"> 
					<span>SMS</span>
					<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> 
				</div>
				<div> 
					<a class="links" href="{% url 'main:profile' %}">Portfolio</a> <hr>
				<a class="links" href="{% url 'main:game' %}">Market</a> <hr>
				<a class="links" href="{% url 'main:leaderboard' %}">Leaderboard</a> <hr> 
				<a class="links" href="{% url 'main:news' %}">News </a> <hr>
				<a class="links" href="{% url 'main:logout' %}">Logout</a> <hr>
				</div>
			</div>
		</div>

	
	

				 <!-- The Modal -->
		<div id="myModal" class="modal">

		  <!-- Modal content -->
		 	<div class="modal-content">
			    <div class="modal-header">
			      	<span class="close" id="close">&times;</span>
			      	<h2>Buy!</h2>
			    </div>
			    <div class="modal-body">
			      	<p>Enter stocks to buy</p>
			      	<p><input type="number" min="0" value="0" class="counter" id="purchaseAmount"></p>
			      	<p class="errorText"></p>
			    </div>
			    <div class="modal-footer">
			    	<button onclick="buyStocks()" class="myButton"> Confirm Purchase </button>
			    </div>
			</div>

		</div>


		<!-- The Modal -->
		<div id="myModals" class="modal">

		  <!-- Modal content -->
		 	<div class="modal-content">
			    <div class="modal-header">
			      	<span class="close" id="closes">&times;</span>
			      	<h2>Sell</h2>
			    </div>
			    <div class="modal-body">
			      	<p>Enter stocks to Sell</p>
			      	<p><input type="number" min="0" value="0" class="counter"  id="sellAmount"></p>
			      	<p class="errorText"></p>
			    </div>
			    <div class="modal-footer">
			    	<button onclick="sellStocks()" class="myButton"> Confirm Sell </button>
			    </div>
			</div>

		</div>



	</div>

<script type="text/javascript" src="{% static 'main/js/stockDetails.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/userDetails.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/market.js' %}" ></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'main/js/conversionRate.js' %}" ></script>	
<script type="text/javascript" src="{% static 'main/js/status.js' %}"></script>
<script type="text/javascript">
	// Get the modal
	var modal = document.getElementById('myModal');
	var modals = document.getElementById('myModals');
	var sidenav = document.getElementById('mySidenav');
	// Get the button that opens the modal
	var btn = document.getElementById("myBtn");

	// Get the <span> element that closes the modal
	var span = document.getElementById("close");
	var spans = document.getElementById("closes");
	// When the user clicks the button, open the modal
	var stockId;
	function modalOpen(id) {
	    modal.style.display = "block";
	    stockId = id;
	}

	function modalOpenS(id) {
		modals.style.display = "block";
	    stockId = id;
	}

	// When the user clicks on <span> (x), close the modal
	span.onclick = function() {
	    modal.style.display = "none";
	}
	spans.onclick = function() {
	    modals.style.display = "none";
	}

	// When the user clicks anywhere outside of the modal, close it
	window.onclick = function(event) {
	    if (event.target == modal || event.target == modals) {
	        modal.style.display = "none";
	        modals.style.display = "none";
	    }
	}

	var timeout = setTimeout("location.reload(true);",60000);
  function resetTimeout() {
    clearTimeout(timeout);
    timeout = setTimeout("location.reload(true);",60000);
  }




</script>

</body>
</html>

SMS_18/main/templates/main/international.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Stock Market Stimulation</title>
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
	<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/home.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/template.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
	<div class="container">
			<div class="header">
				<!-- <div class="title"> <span> STOCK MARKET SIMULATION </span> </div> -->
				<div class="profile">
					<div class="user user1" id="userName"></div>
					<div class="user user2">Balance: &#36; 
						<span  id="userBalance"></span> 
						<span class="conversionRate"> (&#36 1 = &#8377 <span id="conversionRate"></span>)</span>
						<span class="hamburgerIcon"onclick="openNav()">&#9776;</span></div>
				</div>
				<div class="navbar">

		  			<a href="{% url 'main:game' %}"><div class="nav"><span>Indian</span> </div> </a>
		  			<a href="{% url 'main:international' %}"> <div class="nav active" ><span>International</span> </div> </a>
				</div>
			</div>
		<div class="main">
			<div class="stock">
				<div class="shown">
					<div class="name" id="stockName"><b>Stock Name</b></div>
					<div class="price"><b>Stock Price</b></div>
				</div>
				<!-- <div class="hidden">
					<div class="buy" id="myBtn"><button onclick="modalOpen()">BUY</button></div>
					
					<div class="sell" id="myBtn"><button class="button" onclick="modalOpenS()">SELL</button></div> -->

					<!-- <div class=""> <button id="myBtn" onclick="modalOpen()">Open Modal</button> </div> -->
				</div>
			</div>
		</div>

		

		<div class="sideBar">
			<div id="mySidenav" class="sidenav">
				<div class="closebtndiv"> 
					<span>SMS</span>
					<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> 
				</div>
				<div> 
					<a class="links" href="{% url 'main:profile' %}">Portfolio</a> <hr>
				<a class="links" href="{% url 'main:game' %}">Market</a> <hr>
				<a class="links" href="{% url 'main:leaderboard' %}">Leaderboard</a> <hr> 
				<a class="links" href="{% url 'main:news' %}">News </a> <hr>
				<a class="links" href="{% url 'main:logout' %}">Logout</a> <hr>
				</div>
			</div>
		</div>


	
	

			<!-- The Modal -->
		<div id="myModal" class="modal">

		  <!-- Modal content -->
		 	<div class="modal-content">
			    <div class="modal-header">
			      	<span class="close" id="close">&times;</span>
			      	<h2>Buy!</h2>
			    </div>
			    <div class="modal-body">
			      	<p>Enter stocks to buy</p>
			      	<p><input type="number" min="0" value="0" class="counter" id="purchaseAmount"></p>
			    	<p class="errorText"></p>
			    </div>
			    <div class="modal-footer">
			    	<button onclick="buyStocks()" class="myButton"> Confirm Purchase </button>
			    </div>
			</div>

		</div>


		<!-- The Modal -->
		<div id="myModals" class="modal">

		  <!-- Modal content -->
		 	<div class="modal-content">
			    <div class="modal-header">
			      	<span class="close" id="closes">&times;</span>
			      	<h2>Sell</h2>
			    </div>
			    <div class="modal-body">
			      	<p>Enter stocks to Sell</p>
			      	<p><input type="number" min="0" value="0" class="counter"  id="sellAmount"></p>
			    	<p class="errorText"></p>
			    </div>
			    <div class="modal-footer">
			    	<button onclick="sellStocks()" class="myButton"> Confirm Sell </button>
			    </div>
			</div>

		</div>



	</div>
	

<script type="text/javascript" src="{% static 'main/js/nycMarket.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/nycUserDetails.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/market.js' %}"> </script>
<script type="text/javascript" src="{% static 'main/js/conversionRate.js' %}" ></script>
<script type="text/javascript" src="{% static 'main/js/status.js' %}" ></script>	
<script type="text/javascript">
	// Get the modal
	var modal = document.getElementById('myModal');
	var modals = document.getElementById('myModals');
	var sidenav = document.getElementById('mySidenav');
	// Get the button that opens the modal
	var btn = document.getElementById("myBtn");

	// Get the <span> element that closes the modal
	var span = document.getElementById("close");
	var spans = document.getElementById("closes");
	// When the user clicks the button, open the modal
	var stockId;
	function modalOpen(id) {
	    modal.style.display = "block";
	    stockId = id;
	}

	function modalOpenS(id) {
		modals.style.display = "block";
	    stockId = id;
	}

	// When the user clicks on <span> (x), close the modal
	span.onclick = function() {
	    modal.style.display = "none";
	}
	spans.onclick = function() {
	    modals.style.display = "none";
	}

	// When the user clicks anywhere outside of the modal, close it
	window.onclick = function(event) {
	    if (event.target == modal || event.target == modals) {
	        modal.style.display = "none";
	        modals.style.display = "none";
	    }
	}

var timeout = setTimeout("location.reload(true);",60000);
  function resetTimeout() {
    clearTimeout(timeout);
    timeout = setTimeout("location.reload(true);",60000);
  }




</script>

</body>
</html>

SMS_18/main/templates/main/leaderboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Leaderboard</title>
	<meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/leaderboard.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/css/template.css' %}">
	<script type="text/javascript" src="{% static 'main/js/userDetails.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/leaderboard.js' %}"></script>
	<script type="text/javascript" src="{% static 'main/js/conversionRate.js' %}" ></script>
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
	<div class="container">
		<div class="header header1">
				<!-- <div class="title"> <span> STOCK MARKET SIMULATION </span> </div> -->
				<div class="profile profile1">
					<div class="user user1" id="userName"></div>
					<div class="user user2">Balance: &#8377 
						<span  id="userBalance"></span>
						<span class="conversionRate"> (&#36 1 = &#8377 <span id="conversionRate"></span>)</span>
						<span class="hamburgerIcon"onclick="openNav()">&#9776;</span></div>
				</div>
				<!-- <div class="navbar">

					<a href="{% url 'main:international' %}"> <div class="nav"><span>International</span> </div> </a>
		  			<a href="{% url 'main:game' %}"><div class="nav"><span>Indian</span> </div> </a>

				</div> -->
			</div>
		<div class="main main1">
		</div>

		<div id="mySidenav" class="sidenav">

			<div class="closebtndiv"> 
				<span>SMS</span>
				<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> 
			</div>
			<div> 
				<a class="links" href="{% url 'main:profile' %}">Portfolio</a> <hr>
				<a class="links" href="{% url 'main:game' %}">Market</a> <hr>
				<a class="links" href="{% url 'main:leaderboard' %}">Leaderboard</a> <hr> 
				<a class="links" href="{% url 'main:news' %}">News </a> <hr>
				<a class="links" href="{% url 'main:logout' %}">Logout</a> <hr>
			</div>
		</div>


	</div>
</body>
</html>

SMS_18/main/templates/main/profileCreate.html
<html>
<script>
sessionStorage.setItem("email", '{{ email }}');
window.location = '{{ url }}';
</script>
</html>